#! /bin/sh
### BEGIN INIT INFO
# Provides: stress
# Required-Start: $remote_fs $syslog $network
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Stress Tests
# Description: This file starts stress tests
# 
### END INIT INFO

DIR=/opt/

case "$1" in
 start)
   su root -c $DIR/stress.sh
   ;;
 *)
   echo "Usage: stress {start|stop}" >&2
   exit 3
   ;;
esac